<a href="https://colab.research.google.com/github/AnkitSingh028/Data-Analytics-Codes/blob/main/MatrixOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Input matrix dimensions
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))

# Input Matrix A
print("Enter elements of Matrix A:")
A = np.array([[float(input()) for j in range(c)] for i in range(r)])

# Input Matrix B
print("Enter elements of Matrix B:")
B = np.array([[float(input()) for j in range(c)] for i in range(r)])

# Display matrices
print("\nMatrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Matrix Addition
print("\nMatrix Addition (A + B):")
print(A + B)

# Matrix Subtraction
print("\nMatrix Subtraction (A - B):")
print(A - B)

# Matrix Multiplication
print("\nMatrix Multiplication (A @ B):")
print(A @ B)

# Transpose
print("\nTranspose of Matrix A:")
print(A.T)

# Inverse
if r == c:
    print("\nInverse of Matrix A:")
    print(np.linalg.inv(A))
else:
    print("\nInverse not possible (Matrix not square)")

# Matrix Division
# A / B = A @ inverse(B)
if r == c and np.linalg.det(B) != 0:
    print("\nMatrix Division (A @ inverse(B)):")
    print(A @ np.linalg.inv(B))
else:
    print("\nMatrix Division not possible (B not invertible)")

Enter number of rows: 2
Enter number of columns: 2
Enter elements of Matrix A:
4
5
6
7
Enter elements of Matrix B:
2
2
5
4

Matrix A:
[[4. 5.]
 [6. 7.]]

Matrix B:
[[2. 2.]
 [5. 4.]]

Matrix Addition (A + B):
[[ 6.  7.]
 [11. 11.]]

Matrix Subtraction (A - B):
[[2. 3.]
 [1. 3.]]

Matrix Multiplication (A @ B):
[[33. 28.]
 [47. 40.]]

Transpose of Matrix A:
[[4. 6.]
 [5. 7.]]

Inverse of Matrix A:
[[-3.5  2.5]
 [ 3.  -2. ]]

Matrix Division (A @ inverse(B)):
[[ 4.5 -1. ]
 [ 5.5 -1. ]]
